// components/nav.tsx
import Link from "next/link";
import './nav.css';

export default function Nav({ activeId }: { activeId: string }) {

    const getActive = (id: string) => {
        return `nav-text ${id === activeId ? "active" : ""}`;
    }

    return (
        <nav className="nav-bar">
            <Link href="/" className={getActive("home")}>Home</Link>
            <ul className="flex gap-6">
                <li><Link href="/#about" className={getActive("about")}>About</Link></li>
                <li><Link href="/#projects" className={getActive("projects")}>Projects</Link></li>
                <li><Link href="/#resume" className={getActive("resume")}>Resume</Link></li>
                <li><Link href="/#contact" className={getActive("contact")}>Contact</Link></li>
            </ul>
        </nav>
    )
}

// redesign/src/lib/components/nav.svelte
<nav class="bg-black text-white p-4 flex justify-between items-center">
	<a href="/" class="hover:text-gray-300 transition-colors">Home</a>
	<ul class="flex gap-6">
		<li><a href="#about" class="hover:text-gray-300 transition-colors">About</a></li>
		<li><a href="#projects" class="hover:text-gray-300 transition-colors">Projects</a></li>
		<li><a href="#resume" class="hover:text-gray-300 transition-colors">Resume</a></li>
		<li><a href="#contact" class="hover:text-gray-300 transition-colors">Contact</a></li>
	</ul>
</nav>
